version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    depends_on:
      - database
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
    environment:
      - DB_HOST=database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=symfony_task_20240802
      - POSTGRES_USER=symfony_task_20240802
      - POSTGRES_PASSWORD=symfony_task_20240802
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email@example.com
      - PGADMIN_DEFAULT_PASSWORD=your_password
